version: '3.8'
services:
  app:
    build: 
      context: .
      # Correct the path to your Dockerfile
      dockerfile: dockerfile
    container_name: fcloudContainer
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_volume:/data/db
